/**
 * Visual Regression Tests
 *
 * Tests for visual consistency using Playwright's built-in screenshot comparison.
 * Baseline screenshots are stored in e2e/visual.spec.ts-snapshots/
 *
 * IMPORTANT: Visual tests are platform-specific.
 * - Linux baselines are generated by .github/workflows/visual-baselines.yml on
 *   the same runner image and real Worker path used by the gating CI job.
 * - Local runs use the matching Darwin/Windows baseline where one exists.
 *
 * Uses Playwright best practices with proper waits for animations.
 *
 * @see specs/research/PLAYWRIGHT-TESTING.md
 */

import {
  test,
  expect,
  waitForAppReady,
  waitForAnimation,
  waitForCollaborationReady,
} from './global-setup';

/**
 * Check if running on a mobile browser project.
 */
function isMobileProject(projectName: string): boolean {
  return projectName.startsWith('mobile-');
}

/**
 * Check if running on WebKit browser.
 * WebKit has different font rendering that causes visual test failures.
 */
function isWebkit(browserName: string): boolean {
  return browserName === 'webkit';
}

/**
 * A fresh session has no tracks, so `.step-cell` does not exist until one is
 * added. Several tests here used to guard on step-cell visibility and quietly
 * capture nothing when that guard was false — which it always was.
 */
async function addKickTrack(page: import('@playwright/test').Page): Promise<void> {
  const kickButton = page.getByRole('button', { name: /808 Kick/i });
  await expect(kickButton).toBeVisible({ timeout: 10000 });
  await kickButton.click();
  await expect(page.locator('.track-row').first()).toBeVisible({ timeout: 5000 });
}

// These tests used to skip wholesale in CI, then ran under continue-on-error
// against the mock backend with stale developer-generated Linux baselines. The
// audit caught nine failures being reported as green. CI now owns the complete
// runner-generated baseline set and executes it against a real Worker.
// WebKit and mobile projects remain skipped per-describe below because their
// baselines are Darwin-only.

// Desktop visual tests use a fixed viewport for consistency
test.describe('Visual Regression (Desktop)', { tag: '@visual' }, () => {
  test.use({ viewport: { width: 1280, height: 720 } });

  test.beforeEach(async ({ page, browserName }) => {
    test.skip(isWebkit(browserName), 'WebKit has different font rendering - visual tests use chromium baselines');
    await page.goto('/');
    await waitForAppReady(page);
    // Wait for animations to settle before screenshots
    await waitForAnimation(page);
  });

  test('sequencer grid appearance', async ({ page }) => {
    const grid = page.locator('.sequencer-grid, .tracks').first();

    if (await grid.isVisible()) {
      await expect(grid).toHaveScreenshot('sequencer-grid.png', {
        maxDiffPixels: 100,
        threshold: 0.2,
      });
    } else {
      await expect(page).toHaveScreenshot('full-page.png', {
        maxDiffPixels: 200,
        threshold: 0.2,
      });
    }
  });

  test('transport controls appearance', async ({ page }) => {
    const transport = page.locator('.transport, .transport-controls').first();
    await expect(transport).toBeVisible();

    await expect(transport).toHaveScreenshot('transport-controls.png', {
      maxDiffPixels: 50,
      threshold: 0.2,
    });
  });

  test('sample picker appearance', async ({ page }) => {
    const picker = page.locator('.sample-picker').first();
    await expect(picker).toBeVisible();

    await expect(picker).toHaveScreenshot('sample-picker.png', {
      maxDiffPixels: 100,
      threshold: 0.2,
    });
  });

  test('track row with active steps', async ({ page }) => {
    // A fresh session has no tracks and therefore no `.step-cell` elements, so
    // the previous `if (stepCount >= 8)` guard was always false and this test
    // captured nothing.
    await addKickTrack(page);

    const stepCells = page.locator('.step-cell');
    await expect(stepCells.first()).toBeVisible();
    expect(await stepCells.count()).toBeGreaterThanOrEqual(13);

    for (const index of [0, 4, 8, 12]) {
      await stepCells.nth(index).click();
      await expect(stepCells.nth(index)).toHaveClass(/active/);
    }

    const trackRow = page.locator('.track-row').first();
    await expect(trackRow).toBeVisible();
    // Real-Worker edits carry the product's 600ms attribution flash. Waiting
    // for the class to disappear observes the actual state instead of using a
    // shorter generic animation delay and snapshotting four different ages.
    await expect(trackRow.locator('.step-cell.remote-flash')).toHaveCount(0, { timeout: 2000 });

    const tracksScroller = page.locator('.tracks');
    await tracksScroller.evaluate((element) => { element.scrollLeft = 0; });

    // The full row is wider than the desktop viewport. Locator screenshots
    // therefore scrolled it under the sticky app header and captured the
    // random presence avatar instead of any track pixels. The step strip fits
    // without scrolling; assert that it is below the header and wholly inside
    // the viewport before treating its pixels as the visual contract.
    const stepStrip = trackRow.locator('.steps');
    const stickyActions = trackRow.locator('.track-right');
    await expect(stickyActions).toBeVisible();
    await stickyActions.evaluate((element) => { element.style.display = 'none'; });

    const [stripBox, headerBox] = await Promise.all([
      stepStrip.boundingBox(),
      page.locator('.app-header').boundingBox(),
    ]);
    expect(stripBox).not.toBeNull();
    expect(headerBox).not.toBeNull();
    expect(stripBox!.y).toBeGreaterThanOrEqual(headerBox!.y + headerBox!.height);
    expect(stripBox!.x + stripBox!.width).toBeLessThanOrEqual(page.viewportSize()!.width);
    expect(await stepStrip.locator('.step-cell').last().evaluate((element) => {
      const box = element.getBoundingClientRect();
      return document.elementFromPoint(box.x + box.width / 2, box.y + box.height / 2) === element;
    })).toBe(true);

    await expect(stepStrip).toHaveScreenshot('track-row-with-steps.png', {
      maxDiffPixels: 100,
      threshold: 0.2,
    });
  });

  test('velocity lane expanded', async ({ page }) => {
    await addKickTrack(page);

    const velocityToggle = page
      .getByRole('button', { name: /velocity/i })
      .or(page.locator('[data-testid="velocity-toggle"], .velocity-toggle'))
      .first();
    await expect(velocityToggle).toBeVisible({ timeout: 5000 });
    await velocityToggle.click();

    const velocityLane = page.locator('.velocity-lane').first();
    await expect(velocityLane).toBeVisible({ timeout: 5000 });

    await expect(velocityLane).toHaveScreenshot('velocity-lane-expanded.png', {
      maxDiffPixels: 100,
      threshold: 0.2,
    });
  });
});

test.describe('Responsive Visual Regression', { tag: '@visual' }, () => {
  test.beforeEach(async ({ browserName }) => {
    test.skip(isWebkit(browserName), 'WebKit has different font rendering - visual tests use chromium baselines');
  });

  test('mobile layout (iPhone)', async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto('/');
    await waitForAppReady(page);
    await waitForAnimation(page);

    // Higher tolerance for responsive layouts due to font rendering variability
    await expect(page).toHaveScreenshot('mobile-layout-iphone.png', {
      maxDiffPixels: 500,
      threshold: 0.2,
    });
  });

  test('tablet layout (iPad)', async ({ page }) => {
    await page.setViewportSize({ width: 768, height: 1024 });
    await page.goto('/');
    await waitForAppReady(page);
    await waitForAnimation(page);

    // Higher tolerance for responsive layouts due to font rendering variability
    await expect(page).toHaveScreenshot('tablet-layout-ipad.png', {
      maxDiffPixels: 500,
      threshold: 0.2,
    });
  });

  test('wide desktop layout', async ({ page }) => {
    await page.setViewportSize({ width: 1920, height: 1080 });
    await page.goto('/');
    await waitForAppReady(page);
    // The pre-push visual contract runs with a real Worker. Capture one named
    // connection state rather than racing Connecting... against Connected.
    await waitForCollaborationReady(page);
    // Presence is covered elsewhere. Its generated animal/color is deliberately
    // random and must not become an accidental pixel-baseline dependency. A CSS
    // mask is deterministic whether the first presence frame has mounted yet.
    await page.addStyleTag({
      content: '.avatar-stack { visibility: hidden !important; }',
    });
    await waitForAnimation(page);

    // Higher tolerance for responsive layouts due to font rendering variability
    await expect(page).toHaveScreenshot('desktop-wide.png', {
      maxDiffPixels: 500,
      threshold: 0.2,
    });
  });
});

test.describe('Interaction State Screenshots', { tag: '@visual' }, () => {
  test.beforeEach(async ({ browserName }) => {
    test.skip(isWebkit(browserName), 'WebKit has different font rendering - visual tests use chromium baselines');
  });

  test('button hover states', async ({ page }, testInfo) => {
    test.skip(isMobileProject(testInfo.project.name), 'Desktop-only - hover not available on touch devices');
    await page.goto('/');
    await waitForAppReady(page);

    const playButton = page.getByRole('button', { name: /play/i })
      .or(page.locator('[data-testid="play-button"]'))
      .or(page.locator('.transport button').first());

    await expect(playButton).toBeVisible();
    await playButton.hover();
    await waitForAnimation(page);

    await expect(playButton).toHaveScreenshot('play-button-hover.png', {
      maxDiffPixels: 50,
      threshold: 0.3,
    });
  });

  test('step cell active state', async ({ page }) => {
    await page.goto('/');
    await waitForAppReady(page);
    await addKickTrack(page);

    const stepCell = page.locator('.step-cell').first();
    await expect(stepCell).toBeVisible();

    await stepCell.click();
    await expect(stepCell).toHaveClass(/active/);

    await expect(stepCell).toHaveScreenshot('step-cell-active.png', {
      maxDiffPixels: 20,
      threshold: 0.2,
    });
  });

  test('step cell inactive state', async ({ page }) => {
    await page.goto('/');
    await waitForAppReady(page);
    await addKickTrack(page);

    const stepCell = page.locator('.step-cell').nth(5);
    await expect(stepCell).toBeVisible();
    // New tracks start empty, so this cell should already be inactive.
    await expect(stepCell).not.toHaveClass(/active/);

    await expect(stepCell).toHaveScreenshot('step-cell-inactive.png', {
      maxDiffPixels: 20,
      threshold: 0.2,
    });
  });
});
