import { beforeAll, describe, expect, it } from 'vitest';
import { INSTRUMENT_CATEGORIES } from '../components/sample-constants';
import { FakeAudioContext } from './__fakes__/FakeWebAudio';
import { createSynthesizedSamples } from './samples';

/**
 * The samples actually generated by the audio engine and the picker must
 * describe the same IDs.
 */
describe('procedural sample catalogue parity', () => {
  let synthesizedSampleIds: Set<string>;
  const categories = Object.values(INSTRUMENT_CATEGORIES) as unknown as readonly {
    instruments: readonly { id: string; name: string; type: string }[];
  }[];
  const pickerSamples = categories
    .flatMap(category => category.instruments)
    .filter(instrument => instrument.type === 'sample');

  beforeAll(async () => {
    const samples = await createSynthesizedSamples(new FakeAudioContext().asAudioContext());
    synthesizedSampleIds = new Set(samples.keys());
  });

  it('exposes every procedural audio sample in the picker, with no phantoms', () => {
    expect(new Set(pickerSamples.map(instrument => instrument.id))).toEqual(synthesizedSampleIds);
  });

  it('gives every picker sample a non-empty display name', () => {
    for (const instrument of pickerSamples) {
      expect(instrument.name.trim(), `${instrument.id} has no display name`).not.toBe('');
    }
  });
});
