import fs from 'node:fs';
import path from 'node:path';

import {
  evaluateCandidateReadiness,
  type SampleLabCatalog,
} from './sample-lab-core';

const DEFAULT_TEMPLATE = 'sample-lab/index.html';

export function renderSampleLabMarkdown(catalog: SampleLabCatalog): string {
  const lines = [
    '# Sample Lab candidate readiness',
    '',
    '> Generated by Sample Lab. Hard gates and subjective listening are intentionally separate.',
    '',
    '| Candidate | Target | License | Anchors | Readiness | Blockers / review |',
    '|---|---|---|---:|---|---|',
  ];
  for (const candidate of catalog.candidates) {
    const source = catalog.sources.find(item => item.id === candidate.sourceId)!;
    const readiness = evaluateCandidateReadiness(candidate, catalog.sources);
    const notes = [...readiness.blockers, ...readiness.reviewNotes].join('; ') || 'None';
    lines.push(`| ${candidate.label} | \`${candidate.targetInstrument}\` | ${source.license.spdx} | ${candidate.comparisons.length} | ${readiness.level} | ${notes} |`);
  }
  lines.push(
    '',
    '## Decision rule',
    '',
    '- Reject incompatible/ambiguous licensing and objective hard defects before listening.',
    '- Use browser-confirmed, pitch-matched, fair-level A/B for timbre judgments.',
    '- Require at least three low/mid/high anchors before promotion.',
    '- Keep ties and identity mismatches; do not collapse evidence into a weighted score.',
    ''
  );
  return lines.join('\n');
}

function renderRuntimeListeningHtml(catalog: SampleLabCatalog): string {
  const payload = JSON.stringify({
    seed: catalog.randomizationSeed ?? 'keyboardia-sample-lab-v1',
    candidates: catalog.candidates.map(candidate => ({
      id: candidate.id,
      anchors: candidate.comparisons.map(anchor => ({
        id: anchor.id,
        targetMidi: anchor.targetMidi,
        velocity: anchor.velocity ?? 96,
        candidateUrl: anchor.candidate.url,
      })),
    })),
  }).replaceAll('<', '\\u003c');
  return `<!doctype html>
<html lang="en"><meta charset="utf-8"><meta name="viewport" content="width=device-width"><title>Keyboardia runtime listening</title>
<style>body{font:16px system-ui;max-width:800px;margin:40px auto;padding:0 20px;background:#11151d;color:#edf2ff}button{margin:6px;padding:10px 14px;background:#2867d8;color:white;border:0;border-radius:7px}.card{padding:20px;border:1px solid #34405a;border-radius:10px}</style>
<h1>Actual-runtime listening protocol</h1><p>Uses Keyboardia's shipped <code>SampledInstrument</code>, selection, crossfades, round robins, tuning, offsets, loops, and releases. Seed: <code id="seed"></code>.</p><div class="card"><button id="anchors">Low / mid / high</button><button id="dynamics">Velocity 1–127</button><button id="repeat">Eight repeats</button><button id="hold">Held / release</button><button id="stereo">Stereo then mono fold</button><button id="phrase">Runtime phrase</button><button id="stop">Stop</button><p id="status"></p></div>
<script type="module">
import { SampledInstrument } from '/src/audio/sampled-instrument.ts';
const protocol=${payload};document.querySelector('#seed').textContent=protocol.seed;const candidate=protocol.candidates[0],anchor=candidate.anchors[Math.floor(candidate.anchors.length/2)],url=new URL(anchor.candidateUrl,location.href),parts=url.pathname.split('/').filter(Boolean);parts.pop();const instrumentId=parts.pop(),baseUrl='/'+parts.join('/');let context,instrument,monoDestination,sources=[];
async function ready(){if(instrument)return;context=new AudioContext();monoDestination=context.createGain();monoDestination.channelCount=1;monoDestination.channelCountMode='explicit';monoDestination.connect(context.destination);instrument=new SampledInstrument(instrumentId,baseUrl);instrument.initialize(context,context.destination);if(!await instrument.ensureLoaded())throw new Error('Candidate runtime priority set failed to load');await context.resume()}
function stop(){for(const source of sources)try{source.stop()}catch{}sources=[]}
async function play(events){stop();await ready();const start=context.currentTime+.08;for(const event of events){const source=instrument.playNote('lab-'+event.at,event.note,start+event.at,event.duration,event.volume??.7,event.velocity,event.mono?monoDestination:undefined);if(!source)throw new Error('Runtime produced no source for '+JSON.stringify(event));sources.push(source)}document.querySelector('#status').textContent='Scheduled '+events.length+' real-runtime events; load state '+instrument.getLoadState()}
const line=(values,spacing=.45)=>values.map((value,index)=>({at:index*spacing,note:value.note??anchor.targetMidi,velocity:value.velocity??96,duration:value.duration??.28}));
document.querySelector('#anchors').onclick=()=>play(line(candidate.anchors.map(item=>({note:item.targetMidi,velocity:item.velocity})),.65)).catch(show);
document.querySelector('#dynamics').onclick=()=>play(line([1,16,32,48,64,80,96,112,127].map(velocity=>({velocity})),.35)).catch(show);
document.querySelector('#repeat').onclick=()=>play(line(Array.from({length:8},()=>({velocity:96})),.22)).catch(show);
document.querySelector('#hold').onclick=()=>play([{at:0,note:anchor.targetMidi,velocity:96,duration:2.5}]).catch(show);
document.querySelector('#stereo').onclick=()=>play([{at:0,note:anchor.targetMidi,velocity:96,duration:.8},{at:1.1,note:anchor.targetMidi,velocity:96,duration:.8,mono:true}]).catch(show);
document.querySelector('#phrase').onclick=()=>play(line([0,1,2,1,0,2,1,0].map((index,i)=>({note:candidate.anchors[index%candidate.anchors.length].targetMidi,velocity:[48,80,112,64][i%4]})),.3)).catch(show);
document.querySelector('#stop').onclick=stop;function show(error){document.querySelector('#status').textContent=String(error)}
</script></html>`;
}

export function buildSampleLabFiles(
  catalog: SampleLabCatalog,
  output: string,
  templatePath = DEFAULT_TEMPLATE
): { html: string; runtimeHtml: string; catalog: string; readme: string } {
  const enriched = {
    ...catalog,
    candidates: catalog.candidates.map(candidate => ({
      ...candidate,
      readiness: evaluateCandidateReadiness(candidate, catalog.sources),
    })),
  };
  fs.mkdirSync(output, { recursive: true });
  const htmlOutput = path.join(path.dirname(output), 'sample-lab.html');
  const template = fs.readFileSync(templatePath, 'utf8').replace(
    './__sample-lab/catalog.json',
    `./${path.basename(output)}/catalog.json`
  );
  const runtimeHtmlOutput = path.join(path.dirname(output), 'runtime-listening.html');
  const catalogOutput = path.join(output, 'catalog.json');
  const readmeOutput = path.join(output, 'README.md');
  fs.writeFileSync(htmlOutput, template);
  fs.writeFileSync(runtimeHtmlOutput, renderRuntimeListeningHtml(catalog));
  fs.writeFileSync(catalogOutput, `${JSON.stringify(enriched, null, 2)}\n`);
  fs.writeFileSync(readmeOutput, `${renderSampleLabMarkdown(catalog)}\n## Runtime protocol\n\nOpen \`../runtime-listening.html\` through Vite for low/mid/high anchors, dynamics, repetition, held release/loops, and a phrase using the actual sampled-instrument runtime.\n`);
  return { html: htmlOutput, runtimeHtml: runtimeHtmlOutput, catalog: catalogOutput, readme: readmeOutput };
}
